stepper: 
    baud: 115200
    port: /dev/ttyACM0
    
    n_axes: 2
    interrupt_delay: 4
    debug_print: false
    debug_tick: false
    v_max: 25000
    a_max: 2000000
    axis0:
        step_pin: 2
        direction_pin: 3
        enable_pin: 4
    axis1:
        step_pin: 5
        direction_pin: 6
        enable_pin: 7

  
