stepper: 
    baud: 115200
    
    n_axes: 6
    interrupt_delay: 4
    debug_print: false
    debug_tick: false
    v_max: 25000
    a_max: 2000000
    axis0: # X Axis
        step_pin: 7
        direction_pin: 6
        enable_pin: 5
    axis1: # Y Axis
        step_pin: 4
        direction_pin: 3
        enable_pin: 2
    axis2: # Z Axis
        step_pin: 20
        direction_pin: 19
        enable_pin: 18
    axis3: # C Axis
        step_pin: 10 
        direction_pin: 9
        enable_pin: 8
    axis4: # A Axis
        step_pin: 23
        direction_pin: 22
        enable_pin: 21
    axis5: # B Axis
        step_pin: 17
        direction_pin: 16
        enable_pin: 15
    

  
